# Create Amazon CloudWatch Network Flow Monitor Agent DaemonSet
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ .Values.daemonSet.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "aws-network-flow-monitor-agent.labels" . | nindent 4}}
spec:
  selector:
    matchLabels:
      name: {{ .Values.daemonSet.name }}
      {{- if .Values.podLabels }}
      {{ toYaml .Values.podLabels | indent 6 }}
      {{- end }}
  template:
    metadata:
      {{- if .Values.podAnnotations }}
      annotations:
      {{- range $key, $value := .Values.podAnnotations }}
        {{ $key }}: {{ $value | quote }}
      {{- end }}
      {{- end }}
      labels:
        name: {{ .Values.daemonSet.name }}
        {{- if .Values.podLabels }}
        {{ toYaml .Values.podLabels | indent 8 }}
        {{- end }}
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      hostPID: true
      containers:
        - name: {{ .Values.daemonSet.name }}
          image: {{ include "aws-network-flow-monitor-agent.image" . }}
          securityContext:
            privileged: true
          resources: {{ toYaml .Values.resources | nindent 12 }}
          {{- if eq .Values.env.OPEN_METRICS "on" }}
          ports:
            - name: metrics
              containerPort: {{ .Values.env.OPEN_METRICS_PORT | int }}
              protocol: TCP
          {{- end }}
          env:
            {{- range $key, $value := .Values.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
            - name: K8S_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: K8S_POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: K8S_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            {{- if .Values.caCerts.enabled }}
            - name: AWS_CA_BUNDLE
              value: {{ .Values.caCerts.mountPath }}/{{ .Values.caCerts.fileName }}
            - name: SSL_CERT_FILE
              value: {{ .Values.caCerts.mountPath }}/{{ .Values.caCerts.fileName }}
            {{- end }}
          {{- if .Values.caCerts.enabled }}
          volumeMounts:
            - name: ca-bundle
              mountPath: {{ .Values.caCerts.mountPath }}
              subPath: {{ .Values.caCerts.fileName }}
              readOnly: true
          {{- end }}
      {{- if .Values.caCerts.enabled }}
      volumes:
        - name: ca-bundle
          secret:
            secretName: {{ .Values.caCerts.secretName }}
            {{- if .Values.caCerts.secretKey }}
            items:
              - key: {{ .Values.caCerts.secretKey }}
                path: {{ .Values.caCerts.fileName }}
            {{- end }}
      {{- end }}
      nodeSelector:
        kubernetes.io/os: linux
      terminationGracePeriodSeconds: 5
      serviceAccountName: {{ .Values.serviceAccount.name }}
      {{- with .Values.priorityClassName }}
      priorityClassName: {{ . }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity: {{- toYaml . | nindent 8 }}
      {{- end }}